### ISSUE TITLE
Can't get matched intent as a variable

### ISSUE THREAD

**Issue by sriramsv** [treethought/flask-assistant#10]
There is no way to get the the matched intent name in the code workflow other than having a decorator for each intent.If there is a way to extract the name of the matched intent then we could do a dynamic matching of intents and possibly map functions to match intent names.Cleaner and efficient code this way!

**Comment by treethought** [comment]
Hey sorry about the late reply, been super busy. I've pushed a commit to expose the matched intent as a local proxy. You can now import `intent` and refer to it as the currently matched intent.

**Comment by sriramsv** [comment]
so if I use a local variable intent under any assist.action decorator, it would reflect the matched intent?

**Comment by treethought** [comment]
It's actually a [context local](http://werkzeug.pocoo.org/docs/0.12/local/) (sepcifically LocalProxy). The value returned by referencing `intent` will be the intent matched for the current request. It can be used anywhere within the flask application context.

To use it:
```
from flask_assistant import Assistant, tell, intent
 .... 

@assist.action('SomeIntent')
def action_func():
    speech = "You have matched the intent named {}".format(intent)
    return tell(speech)
```

This would return a response to API.AI saying "you have matched the intent named SomeIntent".

Make sure you have updated to the latest version `pip install -U flask-assistant`

**Comment by sriramsv** [comment]
Getting the following errors:

```10:40:35 PM web.1 |  [2017-05-25 22:40:35,259] ERROR in app: Exception on / [POST]
                                                                                                                                                            │10:40:35 PM web.1 |  Traceback (most recent call last):
                                                                                                                                                            │10:40:35 PM web.1 |    File "/home/sriram/projects/apiaihandler/env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
                                                                                                                                                            │10:40:35 PM web.1 |      response = self.full_dispatch_request()
                                                                                                                                                            │10:40:35 PM web.1 |    File "/home/sriram/projects/apiaihandler/env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
                                                                                                                                                            │10:40:35 PM web.1 |      rv = self.handle_user_exception(e)
                                                                                                                                                            │10:40:35 PM web.1 |    File "/home/sriram/projects/apiaihandler/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
                                                                                                                                                            │10:40:35 PM web.1 |      reraise(exc_type, exc_value, tb)
                                                                                                                                                            │10:40:35 PM web.1 |    File "/home/sriram/projects/apiaihandler/env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
                                                                                                                                                            │10:40:35 PM web.1 |      rv = self.dispatch_request()
                                                                                                                                                            │10:40:35 PM web.1 |    File "/home/sriram/projects/apiaihandler/env/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
                                                                                                                                                            │10:40:35 PM web.1 |      return self.view_functions[rule.endpoint](**req.view_args)
                                                                                                                                                            │10:40:35 PM web.1 |    File "/home/sriram/projects/apiaihandler/env/local/lib/python2.7/site-packages/flask_assistant/core.py", line 255, in _flask_assitant
                                                                                                                                                            │_view_func
                                                                                                                                                            │10:40:35 PM web.1 |      result = self._map_intent_to_view_func(view_func)()
                                                                                                                                                            │10:40:35 PM web.1 |    File "/home/sriram/projects/apiaihandler/application/__init__.py", line 58, in train
                                                                                                                                                            │10:40:35 PM web.1 |      print intent
                                                                                                                                                            │10:40:35 PM web.1 |    File "/home/sriram/projects/apiaihandler/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 366, in <lambda>
                                                                                                                                                            │10:40:35 PM web.1 |      __str__ = lambda x: str(x._get_current_object())
                                                                                                                                                            │10:40:35 PM web.1 |    File "/home/sriram/projects/apiaihandler/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
                                                                                                                                                            │10:40:35 PM web.1 |      return self.__local()
                                                                                                                                                            │10:40:35 PM web.1 |    File "/home/sriram/projects/apiaihandler/env/local/lib/python2.7/site-packages/flask_assistant/core.py", line 32, in <lambda>
                                                                                                                                                            │10:40:35 PM web.1 |      intent = LocalProxy(lambda: find_assistant().assist.intent)
                                                                                                                                                            │10:40:35 PM web.1 |  AttributeError: 'Assistant' object has no attribute 'assist'
```

**Comment by sriramsv** [comment]
https://github.com/treethought/flask-assistant/pull/14

**Comment by sriramsv** [comment]
also, it would be useful if we have an action to match any wildcard intent and route the action  by intent local proxy.

something like:

```python

@assist.action
def action_forward(*args,**kwargs):
  r=plugin_source.load_plugin(intent)
    return tell(r.answer)
```
