### ISSUE TITLE
Running schema command fails

### ISSUE THREAD

**Issue by alexmarginean16** [treethought/flask-assistant#113]
I tried the quick start guide but I seem to get stuck at running `schema` command.
When I run `schema webhook.py` I get:

```
Traceback (most recent call last):
 File "/Users/alexmarginean/Documents/Projects/travelrr-google-assistant/venv/bin/schema", line 7, in <module>
    from api_ai.cli import schema
  File "/Users/alexmarginean/Documents/Projects/travelrr-google-assistant/venv/lib/python3.7/site-packages/api_ai/cli.py", line 15, in <module>
    "Schema generation and management is not yet available for Dialogflow V2, please define intents and entities in the Dialogflow console"
DeprecationWarning: Schema generation and management is not yet available for Dialogflow V2, please define intents and entities in the Dialogflow console
```

I tried so many different stuff but can't seem to work it out :/

**Comment by treethought** [comment]
Hi @alexmarginean16, I have not yet updated the schema functionality to support the dialogflow V2 API. That's why the command results in the depreciation warning.

If really need to use the schema command instead of defining everything in the console, you can install flask-assistant version 0.2.96 and switch your dialogflow agent to use V1.  ( you may also be able to then switch back to V2 and reinstall the latest version of flask-assistant)

I do intend to bring back support for the schema command.

**Comment by alexmarginean16** [comment]
I'm new to theese stuff and I'm still learning. I wasn't even sure how the schema command works (but as you mentioned and read in the docs I think it defines everything based on your code without going into the console). I installed the older version of `flask-assistant` and switched to V1 but now I get different errors.

```
Traceback (most recent call last):
  File "/Users/alexmarginean/Documents/Projects/travelrr-google-assistant/venv/bin/schema", line 11, in <module>
    load_entry_point('Flask-Assistant==0.2.96', 'console_scripts', 'schema')()
  File "/Users/alexmarginean/Documents/Projects/travelrr-google-assistant/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/alexmarginean/Documents/Projects/travelrr-google-assistant/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Users/alexmarginean/Documents/Projects/travelrr-google-assistant/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Users/alexmarginean/Documents/Projects/travelrr-google-assistant/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/alexmarginean/Documents/Projects/travelrr-google-assistant/venv/lib/python3.7/site-packages/api_ai/cli.py", line 4, in <module>
    from flask_assistant.utils import get_assistant
  File "/Users/alexmarginean/Documents/Projects/travelrr-google-assistant/venv/lib/python3.7/site-packages/flask_assistant/__init__.py", line 9, in <module>
    from flask_assistant.core import (
  File "/Users/alexmarginean/Documents/Projects/travelrr-google-assistant/venv/lib/python3.7/site-packages/flask_assistant/core.py", line 7, in <module>
    import aniso8601
ModuleNotFoundError: No module named 'aniso8601'
```

I think I should try to define them manually and might be better. Hope I will be able to do it. :)

**Comment by treethought** [comment]
no worries, try `pip install aniso8601`.

**Comment by alexmarginean16** [comment]
I tried but it then gives indentation errors and stuff. I switched back to V2 and the latest version of `flask-assistant`. Is there a guide or getting started documentation that doesn't use the`schema` command?

**Comment by treethought** [comment]
hmm, any indentation issues wouldn't be caused by flask-assistant. That sounds like maybe something related to your actual code?

And for getting started with creating intents and entities etc, I would just checkout the [Dialogflow docs](https://dialogflow.com/docs/getting-started)
