### ISSUE TITLE
NoneType error when running schema command

### ISSUE THREAD

**Issue by BuggeringHell** [treethought/flask-assistant#12]
I get the following error when trying to run the schema command for the pizza topping sample in Python 2.7.13:
```
"No API.AI Client Access Token set. You will be able to query the agent"
"No API.AI Client Access Token set. You will be able to query the agent"
"No API.AI Client Access Token set. You will be able to query the agent"
"No API.AI Client Access Token set. You will be able to query the agent"
"No API.AI Client Access Token set. You will be able to query the agent"
Generating intent schema...
Traceback (most recent call last):
  File "c:\python27\scripts\schema-script.py", line 9, in <module>
    load_entry_point('Flask-Assistant==0.2.3', 'console_scripts', 'schema')()
  File "c:\python27\lib\site-packages\api_ai\cli.py", line 72, in schema
    intents.generate()
  File "c:\python27\lib\site-packages\api_ai\schema_handlers.py", line 218, in generate
    for intent in self.app_intents:
  File "c:\python27\lib\site-packages\api_ai\schema_handlers.py", line 114, in app_intents
    intent = self.build_intent(intent_name)
  File "c:\python27\lib\site-packages\api_ai\schema_handlers.py", line 123, in build_intent
    self.build_user_says(new_intent)  # TODO
  File "c:\python27\lib\site-packages\api_ai\schema_handlers.py", line 173, in build_user_says
    intent_data = raw.get(intent.name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by treethought** [comment]
This should be fixed now in 0.2.5. Try updating to the latest version with pip.
`pip install -U flask-assistant`pip
