### ISSUE TITLE
StopIteration when running schema

### ISSUE THREAD

**Issue by advak** [treethought/flask-assistant#20]
I tried running schema webhook.py after following the instructions in the Quick Start:
http://flask-assistant.readthedocs.io/en/latest/quick_start.html#schema

I got:
`Traceback (most recent call last):
  File "/usr/local/bin/schema", line 11, in <module>
    sys.exit(schema())
  File "/Users/advak/apiainew/lib/python3.6/site-packages/api_ai/cli.py", line 74, in schema
    entities.generate()
  File "/Users/advak/apiainew/lib/python3.6/site-packages/api_ai/schema_handlers.py", line 289, in generate
    entity = self.push_entity(entity)
  File "/Users/advak/apiainew/lib/python3.6/site-packages/api_ai/schema_handlers.py", line 281, in push_entity
    entity = self.register(entity)
  File "/Users/advak/apiainew/lib/python3.6/site-packages/api_ai/schema_handlers.py", line 263, in register
    entity.id = next(i.id for i in self.api.agent_entities if i.name == entity.name)`

**Comment by mianos** [comment]
How did you fix this?
