### ISSUE TITLE
schema is throwing an import error

### ISSUE THREAD

**Issue by sharkwheels** [treethought/flask-assistant#81]
Weird thing. Maybe someone can provide some insight. I'm getting a AttributeError: 'NoneType' object has no attribute 'loader' error when trying to run 'schema webhook.py'. I'm using Python 3.6 in a virtual environment, just wondering if anyone else is running into this?

```
Traceback (most recent call last):
  File "/Users/nadinelessio/Documents/school/iot_lab/prototypes/officemate/venv/bin/schema", line 11, in <module>
    sys.exit(schema())
  File "/Users/nadinelessio/Documents/school/iot_lab/prototypes/officemate/venv/lib/python3.6/site-packages/api_ai/cli.py", line 47, in schema
    assist = get_assistant(filename)
  File "/Users/nadinelessio/Documents/school/iot_lab/prototypes/officemate/venv/lib/python3.6/site-packages/flask_assistant/utils.py", line 32, in get_assistant
    agent_name, os.path.join(os.getcwd(), filename))
  File "/Users/nadinelessio/Documents/school/iot_lab/prototypes/officemate/venv/lib/python3.6/site-packages/flask_assistant/utils.py", line 15, in import_with_3
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 568, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

Its seems to be not liking: module = importlib.util.module_from_spec(spec). 

Thoughts?

**Comment by jsemig** [comment]
Right now only Dialogflow API V1 is supported, can you double check in your settings that you are using V1. All new projects are automatically started with V2 so you will have to downgrade.

**Comment by sharkwheels** [comment]
Switching to V1 did not solve it. But that is good to know.

**Comment by treethought** [comment]
@sharkwheels are you still experiencing this error?
