### ISSUE TITLE
KeyError: 'originalRequest' error

### ISSUE THREAD

**Issue by sharkwheels** [treethought/flask-assistant#87]
Possible bug, maybe just a strange platform inconsistency. Figured I'd post it as an FYI. See if anyone might have some insight. 

When testing w/ Actions on Google simulator, no issues. When testing on my google home speaker, also no issues. But trying to test in the dialogflow side test panel renders this gnarly error:

```
Traceback (most recent call last):
  File "/home/pi/projects/keras_google/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/projects/keras_google/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pi/projects/keras_google/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/projects/keras_google/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pi/projects/keras_google/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/projects/keras_google/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/projects/keras_google/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/projects/keras_google/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pi/projects/keras_google/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/projects/keras_google/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/projects/keras_google/lib/python3.5/site-packages/flask_assistant/core.py", line 289, in _flask_assitant_view_func
    user_obj = self.request['originalRequest']['data']['user']
KeyError: 'originalRequest'
```

**Comment by gmolau** [comment]
This happened because the `originalRequest` represents data send from Actions on Google to Dialogflow, which is not there if you invoke your app via Dialogflow directly. #90 fixes this.
