### ISSUE TITLE
Action functions can't handle type hints

### ISSUE THREAD

**Issue by gmolau** [treethought/flask-assistant#89]
Trying to use type hints for action function parameters returns this error:

```
Traceback (most recent call last):
  File "<project_dir>/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "<project_dir>/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "<project_dir>/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<project_dir>/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "<project_dir>/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "<project_dir>/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "<project_dir>/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "<project_dir>/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "<project_dir>/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "<project_dir>/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<project_dir>/venv/lib/python3.6/site-packages/flask_assistant/core.py", line 261, in _flask_assitant_view_func
    result = self._map_intent_to_view_func(view_func)()
  File "<project_dir>/venv/lib/python3.6/site-packages/flask_assistant/core.py", line 361, in _map_intent_to_view_func
    arg_names = self._func_args(view_func)
  File "<project_dir>/venv/lib/python3.6/site-packages/flask_assistant/core.py", line 357, in _func_args
    argspec = inspect.getargspec(f)
  File "/usr/local/Cellar/python/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 1075, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
```

The reason for this is that [`inspect.getargspec`](https://docs.python.org/3/library/inspect.html#classes-and-functions) can't handle type annotations and is deprecated in favor of `inspect.getfullargspec`. According to the documentation the latter should be a drop-in replacement, but this should probably be tested.

**Comment by treethought** [comment]
Interesting, thanks for looking into it. I'll check out `getfullargspec` and see if the functionality is the same
