### ISSUE TITLE
KeyError: 'originalRequest' is still not fixed even after the latest commit 

### ISSUE THREAD

**Issue by 1337Phantom** [treethought/flask-assistant#93]
ngrok shows 500 INTERNAL SERVER ERROR and so does Dialogflow. Also for Windows users is there no way to set the Client and dev Access tokens? I'm using SETX CLIENT_ACCESS_TOKEN "token" and the same thing for the dev access token but even without doing that I'm not getting any error messages from flask assistant.

```
from flask import Flask
from flask_assistant import Assistant, tell
from flask_cors import CORS
import searchAPI
app = Flask(__name__)
app.config['ASSIST_ACTIONS_ON_GOOGLE'] = True

cors = CORS(app)
assist = Assistant(app, route='/google')

@assist.action('find-name')
def findName(name: str) -> tell:
    print (name)
    details = searchAPI.getPOSTdata(name) 
    print (details)
    return tell(details)
    

if __name__ == '__main__':    
    app.run('localhost', 8000)

```    
 

This is my code and this is the error I'm getting in IPython console. I'm using conda if that's useful info.

```
Reloaded modules: searchAPI
[2018-05-27 08:46:23,191] ERROR in app: Exception on /google [POST]
Traceback (most recent call last):
  File "C:\Users\USER NAME\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\USER NAME\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\USER NAME\Anaconda3\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\USER NAME\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\USER NAME\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\USER NAME\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\USER NAME\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\USER NAME\Anaconda3\lib\site-packages\flask_assistant\core.py", line 289, in _flask_assitant_view_func
    user_obj = self.request['originalRequest']['data']['user']
KeyError: 'originalRequest'
127.0.0.1 - - [27/May/2018 08:46:23] "POST /google HTTP/1.1" 500 -
```

**Comment by gmolau** [comment]
This was fixed in #90, it just needs to be pushed to PyPI (cc @treethought).
