### ISSUE TITLE
ValueError:Function has keyword-only parameters or annotations, use getfullargspec() API which can support them

### ISSUE THREAD

**Issue by 1337Phantom** [treethought/flask-assistant#94]
I'm sorry if this seems NOOBish but I'm just a beginner and I don't know any better. Please help me.
Also for Windows users is there no way to set the Client and dev Access tokens? I'm using SETX CLIENT_ACCESS_TOKEN "token" and the same thing for the dev access token but even without entering that command flask-assistant gives no error like it usually does for mac and other systems.

```
from flask import Flask
from flask_assistant import Assistant, tell
#from flask_cors import CORS
import searchAPI
app = Flask(__name__)
app.config['ASSIST_ACTIONS_ON_GOOGLE'] = True

#cors = CORS(app)
assist = Assistant(app, route='/google')

@assist.action('find-name',mapping={'name': 'sys.any'})
def findName(name: str):
    print (name)
    #details = searchAPI.getPOSTdata(name) 
    #print (details)
    return tell("Your name is "+name)
    

if __name__ == '__main__':    
    app.run('localhost', 8000)  
    

```      
This is the error I'm getting.

```
* Running on http://localhost:8000/ (Press CTRL+C to quit)
[2018-05-27 14:25:32,124] ERROR in app: Exception on /google [POST]
Traceback (most recent call last):
  File "C:\Users\USERNAME\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\USERNAME\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\USERNAME\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\USERNAME\Anaconda3\lib\site-packages\flask\_compat.py", line 33,
in reraise
    raise value
  File "C:\Users\USERNAME\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\USERNAME\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\USERNAME\Anaconda3\lib\site-packages\flask_assistant\core.py", line 296, in _flask_assitant_view_func
    result = self._map_intent_to_view_func(view_func)()
  File "C:\Users\USERNAME\Anaconda3\lib\site-packages\flask_assistant\core.py", line 481, in _map_intent_to_view_func
    arg_names = self._func_args(view_func)
  File "C:\Users\USERNAME\Anaconda3\lib\site-packages\flask_assistant\core.py", line 477, in _func_args
    argspec = inspect.getargspec(f)
  File "C:\Users\USERNAME\Anaconda3\lib\inspect.py", line 1075, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
127.0.0.1 - - [27/May/2018 14:25:32] "POST /google HTTP/1.1" 500 -
```

**Comment by gmolau** [comment]
This is already reported in #89

**Comment by 1337Phantom** [comment]
Can either of you please help me with the setx problem? I can't get it communicate please help.

**Comment by gmolau** [comment]
I'm not sure what your problem is, the tokens are read via [`os.getenv`](https://github.com/treethought/flask-assistant/blob/f40f81a17bfb5de42023f8713f4440dacb505101/api_ai/api.py#L19) and raise a [`ValueError`](https://github.com/treethought/flask-assistant/blob/f40f81a17bfb5de42023f8713f4440dacb505101/api_ai/api.py#L27) if they are not set. Can you post specific code examples and/or stack traces?

**Comment by treethought** [comment]
The `use getfullargspec()` error should now be fixed with the latest version on pypi.

As for your the setx issue, as @gmolau stated, you should receive an error if the tokens are not set. So it seems they are in fact being set.

I'm going to close this for now, as the setx problem is a separate issue.
